name: test-actions

on:
  push:
    branches:
      - develop
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Test setting version using default parameters
        id: test-setversion
        uses: ./    # Just point to the main folder so the latest code is always used
        with:
          version: '8.8'

      - name: Test output of 'assemblyinfo-update'
        run: echo "AssemblyInfo updated to ${{steps.test-setversion.outputs.version}}"

      - name: Test setting version with custom parameters
        id: test-setversion-with-params
        uses: ./    # Just point to the main folder so the latest code is always used
        with:
          version: '9.9.9-alpha'
          directory: './test/'
          filename: 'SharedAssemblyInfo.cs'
          recursive: false

      - name: Test output of 'assemblyinfo-update'
        run: echo "AssemblyInfo updated to ${{steps.test-setversion-with-params.outputs.version}}"

      - name: Upload updated files
        uses: actions/upload-artifact@v3
        with:
          name: Test results for version '${{steps.test-setversion-with-params.outputs.version}}'
          path: ./test/*.cs
          
      - name: Test setting version with custom parameters
        id: test-setversion-with-params-no-buildnumber
        uses: ./    # Just point to the main folder so the latest code is always used
        with:
          version: '9.9.9.103'
          directory: './test/'
          filename: 'SharedAssemblyInfo.cs'
          recursive: false
          usebuildnumber: false

      - name: Test output of 'assemblyinfo-update'
        run: echo "AssemblyInfo updated to ${{steps.test-setversion-with-params-no-buildnumber.outputs.version}}"
        
      - name: Upload updated files
        uses: actions/upload-artifact@v3
        with:
          name: Test results for version '${{steps.test-setversion-with-params-no-buildnumber.outputs.version}}'
          path: ./test/*.cs  
